Padroniza docker compose
fga-eps-mds/2022-2-Alectrion-FrontEnd pull request #20
Opened 2023-01-26 03:23 UTC by RuanMoura

## Modificações
Criação de docker compose
## Descrição
Criação de um docker compose para padronização dos projetos 
## _Issue_ relacionado
fga-eps-mds/2022-2-Alectrion-DOC#107
## Como foi testado?
Rodando o docker compose localmente.
- [ ] _ ​​correção de bug_
- [x] Nova _feature_

## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.
- [ ] Minhas modificações requerem modificações na documentação atual.
- [x] Atualizei a Documentação
- [ ] Adicionei testes para cobrir minhas modificações.
- [ ] Todos os testes foram aprovados.

2023-01-26 18:00 UTC, ErickGiffoni approved these changes

2023-01-26 21:00 UTC, AlineLermen approved these changes

2023-01-27 15:03 UTC, ErickGiffoni commented
Testando... aguarde para fazer o _merge_

2023-01-27 15:05 UTC, ErickGiffoni reviewed
Espera. Acho que sua _branch_ não está atualizada com a _dev_, porque os testes falharam
Veja isso @RuanMoura

2023-01-27 15:05 UTC, ErickGiffoni requested changes
Atualizar com a _dev_ para os testes passarem

2023-01-27 23:08 UTC, ErickGiffoni commented
Gente @AlineLermen @SamButers @JoaoVitorFarias @RuanMoura vamos testar novamente esse docker-compose, em integração com os outros serviços rodando no docker deles tbm pra ver se tá certinho mesmo, pode ser ?

2023-01-29 15:15 UTC, JoaoVitorFarias approved these changes

2023-01-30 00:40 UTC, AlineLermen approved these changes

2023-01-30 01:12 UTC, merged