Us/07 cadastro de ordem de serviço
fga-eps-mds/2022-2-Alectrion-FrontEnd pull request #21
Opened 2023-01-28 01:35 UTC by JoaoVitorFarias

## Modificações
- Atualização da listagem de ordem de serviço
- Atualização do cadastro de ordem de serviço

## Descrição
Listagem, cadastro e edição de ordem de serviço.

## _Issue_ relacionado
[#16](https://github.com/fga-eps-mds/2022-2-Alectrion-DOC/issues/16)

## Imagens:

## Tipo de modificações
- [x] _ ​​correção de bug_
- [x] Nova _feature_

## Lista de controle:
- [x] Meu código segue a folha de estilos implementada
- [x] Meu _commits_ segue a política de commits do repo.
- [] Adicionei testes para cobrir minhas modificações.
- [] Todos os testes foram aprovados.

2023-01-28 15:30 UTC, ErickGiffoni commented
@JoaoVitorFarias existem conflitos a serem resolvidos ok ?

2023-01-28 22:03 UTC, ErickGiffoni requested changes
@CarlosEduardoMendesdeMesquita @mathonaut ainda existem conflitos a serem resolvidos.
Aproveitem e, depois de resolverem isso, atualizem a _branch_ de vcs com a dev

2023-01-30 02:15 UTC, SamButers requested changes
Não consta situação dos equipamentos (em branco), enquanto na dev está aparecendo corretamente.

2023-01-30 02:28 UTC, SamButers commented
> Não consta situação dos equipamentos (em branco) na tabela de equipamentos, enquanto na dev está aparecendo corretamente. Pode ser consequência de mudança no backend ou frontend.

O problema consta no arquivo src/components/Equipament-Tables/index.tsx:153.
Como a situacao já chega formtado, o handleStatus não retorna corretamente.
Eu colocaria como proposta de mudança, mas como esse problema é consequência das mudanças e não de um arquivo modificado, não consigo comentar a linha do problema.

2023-01-30 02:35 UTC, SamButers approved these changes
Erro no engano.
Tudo certo. 👍

2023-01-30 16:56 UTC, ErickGiffoni approved these changes

2023-01-31 00:39 UTC, AlineLermen approved these changes

2023-01-31 13:06 UTC, merged