Ajustes cadastro ordem servico
fga-eps-mds/2022-2-Alectrion-FrontEnd pull request #30
Opened 2023-02-10 20:41 UTC by AlvaroLeles

## Modificações
Edição de nomes de campos e remoção de campos indesejados em ordem de serviço.
## Descrição

- Editei o nome do campo "Funcional do Entregador" para "RG/Funcional do Entregador" tanto na criação quanto na edição da ordem de serviço
- Removi o campo "N° funcional do recebedor" tanto na criação quanto na edição da ordem de serviço
- Renomeei o campo "Descrição" para "Descrição do problema do equipamento" tanto na criação quanto na edição da ordem de serviço
- Alterei um item de um teste para lidar com essas solicitações

## _Issue_ relacionado
#122 (https://github.com/fga-eps-mds/2022-2-Alectrion-DOC/issues/122)
## Motivação e Contexto
Ajustes solicitados.
## Como foi testado?
Utilização do yarn test:all
## Tipo de modificações
- [x] _ ​​correção de bug_
- [] Nova _feature_

## Lista de controle:
- [x] Meu _commits_ segue a política de commits do repo.
- [] Minhas modificações requerem modificações na documentação atual.
- [] Atualizei a Documentação
- [x] Adicionei testes para cobrir minhas modificações.
- [x] Todos os testes foram aprovados.

2023-02-10 20:54 UTC, SamButers requested changes

2023-02-10 20:54 UTC, SamButers commented on src/components/register-order-service-form/index.tsx
> +      console.log(formik.values)
Remova o console.log.

2023-02-10 20:54 UTC, SamButers commented on src/components/register-order-service-form/index.tsx
> +                sx={{display: 'none'}}
A intenção é remover esse campo?
Qual é o intuito do `display 'none'`?

2023-02-10 20:59 UTC, AlvaroLeles commented on src/components/register-order-service-form/index.tsx
> +                sx={{display: 'none'}}
Sim, é remover o campo, mas como isso é um detalhe que por algum motivo pode querer que seja revertido em algum momento, preferi só esconder o campo ao invés de matá-lo completamente, e é isso que o `display:'none'` faz.

2023-02-10 21:00 UTC, AlvaroLeles commented on src/components/register-order-service-form/index.tsx
> +      console.log(formik.values)
Removido

2023-02-10 21:08 UTC, SamButers approved these changes

2023-02-13 22:25 UTC, ErickGiffoni approved these changes

2023-02-13 22:37 UTC, merged